# Generated by Django 5.2.5 on 2025-08-16 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_questioncodedescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_extra_1',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_extra_2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_extra_3',
        ),
    ]
