# Generated by Django 5.2.5 on 2025-08-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_remove_answer_answer_extra_1_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('question', 'attempt'), name='unique_question_attempt'),
        ),
    ]
